-- return {
-- 	"ray-x/go.nvim",
-- 	dependencies = { -- optional packages
-- 		"ray-x/guihua.lua",
-- 		"neovim/nvim-lspconfig",
-- 		"nvim-treesitter/nvim-treesitter",
-- 	},
-- 	event = { "CmdlineEnter" },
-- 	ft = { "go", "gomod" },
-- 	opts = {
-- 		lsp_inlay_hints = {
-- 			only_current_line = true,
-- 		},
-- 	},
-- 	build = ':lua require("go.install").update_all_sync()', -- if you need to install/update all binaries
-- }
return {
	-- {
	-- 	"ray-x/go.nvim",
	-- 	dependencies = { -- optional packages
	-- 		"ray-x/guihua.lua",
	-- 		"neovim/nvim-lspconfig",
	-- 		"nvim-treesitter/nvim-treesitter",
	-- 	},
	-- 	opts = {
	-- 		lsp_keymaps = false,
	-- 		lsp_semantic_highlights = true,
	-- 		trouble = true,
	-- 	},
	-- 	event = { "CmdlineEnter" },
	-- 	ft = { "go", "gomod" },
	-- 	build = ':lua require("go.install").update_all_sync()', -- if you need to install/update all binaries
	-- },
}
